# Generated by Django 3.0.1 on 2020-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200429_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='coordinates_X',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='coordinates_Y',
            field=models.FloatField(max_length=100),
        ),
    ]
